import { jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
}

export const workspaces = pgTable('workspaces', {
  id: text('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), slug: text('slug').notNull(), description: text('description'), ...timestamps,
})
export const projects = pgTable('projects', {
  id: text('id').primaryKey(), userId: text('user_id').notNull(), workspaceId: text('workspace_id'), name: text('name').notNull(), slug: text('slug').notNull(), description: text('description'), status: text('status').default('active').notNull(), repositoryUrl: text('repository_url'), ...timestamps,
})
export const agents = pgTable('agents', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), name: text('name').notNull(), description: text('description'), status: text('status').default('idle').notNull(), model: text('model'), config: jsonb('config').$type<Record<string, unknown>>().default({}).notNull(), ...timestamps })
export const tasks = pgTable('tasks', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), agentId: text('agent_id'), title: text('title').notNull(), description: text('description'), status: text('status').default('pending').notNull(), priority: text('priority').default('normal').notNull(), dueAt: timestamp('due_at', { withTimezone: true }), metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}).notNull(), ...timestamps })
export const pipelines = pgTable('pipelines', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), name: text('name').notNull(), description: text('description'), status: text('status').default('draft').notNull(), definition: jsonb('definition').$type<Record<string, unknown>>().default({}).notNull(), ...timestamps })
export const chatConversations = pgTable('chat_conversations', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), title: text('title').default('Nova conversa').notNull(), ...timestamps })
export const chatMessages = pgTable('chat_messages', { id: text('id').primaryKey(), conversationId: text('conversation_id'), userId: text('user_id').notNull(), role: text('role').notNull(), content: text('content').notNull(), metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const audits = pgTable('audits', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), action: text('action').notNull(), actor: text('actor'), status: text('status').default('success').notNull(), details: jsonb('details').$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const evidence = pgTable('evidence', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), name: text('name').notNull(), type: text('type').notNull(), uri: text('uri'), checksum: text('checksum'), metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const repositories = pgTable('repositories', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), provider: text('provider').notNull(), name: text('name').notNull(), url: text('url').notNull(), branch: text('branch').default('main').notNull(), status: text('status').default('connected').notNull(), metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}).notNull(), ...timestamps })
export const integrations = pgTable('integrations', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), provider: text('provider').notNull(), name: text('name').notNull(), status: text('status').default('disconnected').notNull(), config: jsonb('config').$type<Record<string, unknown>>().default({}).notNull(), ...timestamps })
export const notifications = pgTable('notifications', { id: text('id').primaryKey(), userId: text('user_id').notNull(), type: text('type').notNull(), title: text('title').notNull(), body: text('body'), readAt: timestamp('read_at', { withTimezone: true }), metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const settings = pgTable('settings', { id: text('id').primaryKey(), userId: text('user_id').notNull(), key: text('key').notNull(), value: jsonb('value').$type<Record<string, unknown>>().default({}).notNull(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() })
export const observabilityEvents = pgTable('observability_events', { id: text('id').primaryKey(), userId: text('user_id').notNull(), projectId: text('project_id'), level: text('level').default('info').notNull(), source: text('source').notNull(), message: text('message').notNull(), metadata: jsonb('metadata').$type<Record<string, unknown>>().default({}).notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })

export const appSchema = { workspaces, projects, agents, tasks, pipelines, chatConversations, chatMessages, audits, evidence, repositories, integrations, notifications, settings, observabilityEvents }
