export const panelRoutes = {
  dashboard: '/app/dashboard',
  projetos: '/app/projetos',
  chat: '/app/chat',
  fontes: '/app/fontes',
  agentes: '/app/agentes',
  pipelines: '/app/pipelines',
  auditorias: '/app/auditorias',
  database: '/app/database',
  integracoes: '/app/integracoes',
  ambiente: '/app/ambiente',
  orquestrador: '/app/orquestrador',
  memoria: '/app/memoria',
  ferramentas: '/app/ferramentas',
  evidencias: '/app/evidencias',
  observabilidade: '/app/observabilidade',
  cli: '/app/cli',
  configuracoes: '/app/configuracoes',
  perfil: '/app/perfil',
  notificacoes: '/app/notificacoes',
} as const

export type PanelRoute = keyof typeof panelRoutes

export const panelNavigation = [
  ['Dashboard', panelRoutes.dashboard, 'dashboard'],
  ['Projetos', panelRoutes.projetos, 'projetos'],
  ['Chat com IA', panelRoutes.chat, 'chat'],
  ['Fontes', panelRoutes.fontes, 'fontes'],
  ['Agentes', panelRoutes.agentes, 'agentes'],
  ['Pipelines', panelRoutes.pipelines, 'pipelines'],
  ['Auditorias', panelRoutes.auditorias, 'auditorias'],
  ['Banco de dados', panelRoutes.database, 'database'],
  ['Integrações', panelRoutes.integracoes, 'integracoes'],
  ['Ambiente', panelRoutes.ambiente, 'ambiente'],
  ['Orquestrador', panelRoutes.orquestrador, 'orquestrador'],
  ['Memória', panelRoutes.memoria, 'memoria'],
  ['Ferramentas', panelRoutes.ferramentas, 'ferramentas'],
  ['Evidências', panelRoutes.evidencias, 'evidencias'],
  ['Observabilidade', panelRoutes.observabilidade, 'observabilidade'],
  ['CLI', panelRoutes.cli, 'cli'],
] as const

export const legacyPanelCopy = {
  projetos: ['Projetos', 'Organize projetos, repositórios e ciclos de engenharia.', 'Conecte um projeto para começar a acompanhar sua operação.'],
  chat: ['Chat com IA', 'Converse com o contexto completo do seu workspace.', 'Faça perguntas sobre código, arquitetura, execução e evidências.'],
  fontes: ['Fontes', 'Mantenha documentos e referências sincronizados.', 'Adicione fontes para enriquecer o contexto dos agentes.'],
  agentes: ['Agentes', 'Crie, configure e monitore agentes de engenharia.', 'Os agentes disponíveis aparecerão aqui quando configurados.'],
  pipelines: ['Pipelines', 'Acompanhe fluxos de execução e seus resultados.', 'Nenhum pipeline foi executado neste workspace.'],
  auditorias: ['Auditorias', 'Consulte eventos, ações e trilhas de auditoria.', 'As atividades auditáveis aparecerão aqui.'],
  database: ['Banco de dados', 'Veja conexões, schemas e estado do banco.', 'Conecte um banco para visualizar informações permitidas.'],
  integracoes: ['Integrações', 'Gerencie GitHub, Vercel, IA, Neon e APIs.', 'Nenhuma integração adicional configurada.'],
  ambiente: ['Ambiente', 'Inspecione runtime, serviços e variáveis configuradas.', 'As informações do ambiente são protegidas e exibidas conforme suas permissões.'],
  orquestrador: ['Orquestrador', 'Coordene fluxos e processos de engenharia.', 'Nenhum fluxo ativo no momento.'],
  memoria: ['Memória', 'Gerencie o contexto persistente dos agentes.', 'A memória do workspace será exibida aqui.'],
  ferramentas: ['Ferramentas', 'Veja as ferramentas disponíveis para os agentes.', 'Nenhuma ferramenta adicional foi habilitada.'],
  evidencias: ['Evidências', 'Consulte artefatos, resultados e validações.', 'As evidências produzidas pelo sistema aparecerão aqui.'],
  observabilidade: ['Observabilidade', 'Monitore logs, métricas, traces e saúde.', 'Nenhum evento recente de observabilidade.'],
  cli: ['CLI', 'Acesse informações e operações da CLI.', 'Instale a CLI para executar operações localmente.'],
  configuracoes: ['Configurações', 'Configure preferências do painel e da aplicação.', 'As configurações do workspace serão exibidas aqui.'],
  perfil: ['Perfil', 'Gerencie seus dados e preferências pessoais.', 'Seu perfil autenticado está ativo.'],
  notificacoes: ['Notificações', 'Acompanhe alertas e atualizações do workspace.', 'Você está em dia.'],
} as const
